name: Notify Discord on Workflow Completion

on:
  workflow_run:
    workflows: [ "Deploy App on Server",  "Docker Image CI" ]  # Triggered after another workflow completes
    types:
      - completed

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        if: always()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
            "content": "**GitHub Action Notification**",
            "embeds": [
              {
                "title": "Workflow: ${{ github.event.workflow_run.name }}",
                "description": "Status: **${{ github.event.workflow_run.conclusion }}**\nCommit: `${{ github.event.workflow_run.head_commit.id }}`\nMessage: _${{ github.event.workflow_run.head_commit.message }}_",
                "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}",
                "color": ${{ github.event.workflow_run.conclusion == 'success' && 65280 || 16711680 }},
                "footer": {
                  "text": "Triggered by: ${{ github.event.workflow_run.actor.login }}"
                }
              }
            ]
          }' ${{ secrets.DISCORD_WEBHOOK }}