name: SSH and Run Script on Server

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed
  workflow_dispatch:

jobs:
  ssh-job:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Run Script on Server
        env:
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          WORKSPACE: /home/${{ secrets.SERVER_USERNAME }}/app/
          EXECUTE: update_app.sh
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no "$SERVER_USERNAME@$SERVER_HOST" "cd $WORKSPACE && sh $EXECUTE"

      - name: Notify Discord on Success
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "The script **update_app.sh** has been successfully executed on the server 🚀!"}' \
          $DISCORD_WEBHOOK

      - name: Notify Discord on Failure
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "❌ The script **update_app.sh** failed to execute on the server."}' \
          $DISCORD_WEBHOOK
